apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mqn8pec06-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mqn8pec06-python 
  name: mqn8pec06-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mqn8pec06-python 
